runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.app

libraries:
- name: certifi
  version: "2017.11.5"
- name: chardet
  version: "3.0.4"
- name: click
  version: "6.7"
- name: dash
  version: "0.19.0"
- name: dash-core-components
  version: "0.14.0"
- name: dash-html-components
  version: "0.8.0"
- name: dash-renderer
  version: "0.11.1"
- name: decorator
  version: "4.1.2"
- name: Flask
  version: "0.12.2"
- name: Flask-Compress 
  version: "1.4.0"
- name: idna
  version: "2.6"
- name: itsdangerous
  version: "0.24"
- name: Jinja2
  version: "2.10"
- name: jsonschema
  version: "2.6.0"
- name: jupyter-core
  version: "4.4.0"
- name: MarkupSafe
  version: "1.0"
- name: nbformat
  version: "4.4.0"
- name: numpy
  version: "1.13.3"
- name: pandas
  version: "0.21.0"
- name: plotly
  version: "2.2.2"
- name: python-dateutil
  version: "2.6.1"
- name: pytz
  version: "2017.3"
- name: requests
  version: "2.18.4"
- name: six
  version: "1.11.0"
- name: traitlets
  version: "4.3.2"
- name: urllib3
  version: "1.22"
- name: Werkzeug
  version: "0.12.2"